package com.space_151958.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Property implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Address of property")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "Age of property")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Locale")
	private java.lang.String locale;
	@org.kie.api.definition.type.Label(value = "Sale Price")
	private java.lang.Integer saeprice;

	public Property() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getLocale() {
		return this.locale;
	}

	public void setLocale(java.lang.String locale) {
		this.locale = locale;
	}

	public java.lang.Integer getSaeprice() {
		return this.saeprice;
	}

	public void setSaeprice(java.lang.Integer saeprice) {
		this.saeprice = saeprice;
	}

	public Property(java.lang.String address, java.lang.Integer age,
			java.lang.String locale, java.lang.Integer saeprice) {
		this.address = address;
		this.age = age;
		this.locale = locale;
		this.saeprice = saeprice;
	}

}